main: gc.nicoarbelaez.GiftCalendar
version: ${project.version}
name: ${project.name}
author: nicoarbelaez
api-version: "1.13"
softdepend: [Vault]
depend: [NBTAPI]

commands:
  giftcalendar:
    description: Main command GiftCalendar
    aliases:
      - giftc
      - gc
      - calendar
